# config/packages/security.yaml
security:
    # Configuration des hashers de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers pour la récupération des utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /user_dashboard
                always_use_default_target_path: false
                use_referer: true
                success_handler: App\Security\LoginSuccessHandler
            lazy: true
            provider: app_user_provider
            logout:
                path: /logout
                # Optionnellement, tu peux configurer les options suivantes si nécessaire :
                # invalidate_session: true
                # csrf_token_generator: security.csrf.token_manager

    # Contrôle d'accès
    access_control:
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

# Configuration pour les tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale pour bcrypt
                time_cost: 3 # Valeur minimale pour argon
                memory_cost: 10 # Valeur minimale pour argon
