twig:
    file_name_pattern: '*.twig'
    form_theme: ['bootstrap_5_layout.html.twig']
    globals:
        category_service: '@App\Service\CategoryService'

when@test:
    twig:
        strict_variables: true
